# Generated by Django 2.0.4 on 2018-04-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('id_no', models.CharField(max_length=20, unique=True)),
                ('photo', models.FileField(upload_to='photos')),
            ],
        ),
    ]
